### ISSUE TITLE
Cannot highlight

### ISSUE THREAD

**Issue by Armixy** [ptsteadman/hexo-theme-corporate#1]
I've enable highlight in _conifg.yml, but still not work.

**Comment by ptsteadman** [comment]
Hi, do you mean code highlighting support?   I did not add any code highlighting library.  

Are you using the code block tag https://hexo.io/docs/tag-plugins.html#Examples-1

I think it would make sense to add support for highlighted code added with the code block tag.

**Comment by Armixy** [comment]
Yes, I have just fixed it through added some code highlighting .styl files from theme 'landscape'.
Then I can highlight my codes through markdown.
For example:
'''cpp
#include <iostream>
using namespace std;
int main()
{
    return 0;
}
'''
PS: Your theme is awesome!

**Comment by ptsteadman** [comment]
Great, feel free to make a PR, would definitely be useful.
